### ISSUE TITLE
Restore subrecipient management UI

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#268]
- Revise subrecipient db table
- Push subrecipients into DB on write
- Do something about conflicts (?)

**Comment by igor47** [comment]
the existing subrecipients ui was not doing any validation! i may have to break out the validation functions or at least expose previously-private methods to validate the updates coming in over the ui.

**Comment by igor47** [comment]
just thinking through the flow here:
1. an upload validates, and creates a subrecipient
2. a later upload includes the same sub-recipient 
3. a user edits the sub-recipient via the ui

at step 2, we currently do not update the `upload_id` of the recipient row. this means that recipients will be associated with a possibly-stale upload (not one of the ones that will be used for the treasury export).

at step 2, we might fail to validate the upload because it does not match the existing recipient. a user will have to either edit the subrecipient in the UI, or edit the spreadsheet

at step 3, how do we know that this has happened? this is important because, at step 1, if we re-validate and discover a subrecipient associated with that upload, we just update it. if it's been updated via the ui, however, then the db state is now authoritative. 

possibly a todo is to add `updated_at`/`updated_by` columns to the table, which are set if the recipient is edited in the UI. then, at step 1, if we find a row that's been created by that same upload, but it's been edited, we fail with a validation error if the row no longer matches.

**Comment by igor47** [comment]
closed by #260
