### ISSUE TITLE
Spreadsheet Upload Validations Incorrect

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/arpa-reporter#361]
There are 3 different errors, but they all stem from the same problem. In each case there is a legitimate value in the field, but errors are being thrown.
Values in template:
EC1 column V: 5500000
EC1 column W: No
Awards > 50K: Family or childcare (capitalization is correct)

![Validation 01](https://user-images.githubusercontent.com/78866741/176002343-9e8f5de5-78c2-4d02-bf1c-928d4e07b583.png)

**Comment by jcomeau1** [comment]
You can use a copy of my test file out on Google Drive: [https://drive.google.com/file/d/1m5zyYHdWhg2twnHOxJf306CxQjPqfvjC/view?usp=sharing](url)

**Comment by igor47** [comment]
the primary sector errors are fixed in #382 

the problem with the EC1 row 13 cols V/W errors is that those don't have column headers in joe's sheet:
![image](https://user-images.githubusercontent.com/200575/176764236-3128ba54-499c-4316-b18c-8b94d056f787.png)

and so we never read them, because when parsing records, we look at the header, here:
![image](https://user-images.githubusercontent.com/200575/176764409-c2a34eab-97da-4089-a172-928b440b598f.png)

and row 3 is set to `TBD`. we could, instead, use the column headers from the rules -- but i'm not sure what else that might break? like, did we ever insert columns in the middle, and if we use the column mapping from the rules, we'll just end up with totally junk data?

**Comment by jcomeau1** [comment]
So in the latest version, v20220620, I did add the metadata in for V, W. I also took care of EC2 columns W, X which had the same issue. If you are using the latest template to drive the logic, it should work.

That said, there are still some questionable fields with the (manual entry) in them. I can't actually find these fields in the output template (they came from the partners). In this instance, we could:
- ignore validation 
- or I could add an appropriate data type and max value if appropriate

Lastly, if you look carefully at the last few treasury identifiers above, you will see there's only one underscore '_c' instead of '__c' but also, the names themselves aren't entirely right. The names must be fixed and I'll do that once Treasury releases their guidance tomorrow.

Does this help?
