### ISSUE TITLE
[Partner submission] [EC: 2 - field name: CapEx Type - col: AE] Some selections trigger an error: "Value for Type_of_Capital_Expenditure_c must be one of the 26 options in the input template

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#427]
**Submitted Description:**
The specific selection triggering an error is "Affordable housing supportive housing or recovery housing" - exactly as I typed it. Possibly a case sensitivity issue or a stealth change from UST that wasn't caught b/c our prior projects never answered this field (no capex).

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5335284314523977491/error1.PNG
https://www.jotform.com/uploads/grants.dev/212695501572052/5335284314523977491/error2.PNG

**Comment by ozzie-chung** [comment]
Hi friends, I am on Github now too.

This one was pretty easy to manually fix, looks like the data validation fields have become misaligned with what is listed in the UST output template.

Looks like only two discrepancies upon closer look:

Affordable housing, supportive housing, or recovery housing (new)
COVID-19 testing sites and laboratories, and acquisition of related equipment (new)

**Comment by jcomeau1** [comment]
Ozzie, just to clarify, it would error out WITHOUT the commas?

**Comment by ozzie-chung** [comment]
Yes, it errors without commas. 

I asked the user for her workbook. She sent it over, I unhid the admin tabs, saw it had no commas, added the commas for that specific cell, sent it back to her. She uploaded it with no problem - so the error cleared after adding commas.

**Comment by jcomeau1** [comment]
Okay. We actually removed the commas based on the last reporting period, but it seems Treasury fixed the issue. This means I should re-add the commas to the appropriate dropdowns. Ugh. I'll validate various field/values within the portal before making this change. I'll also think through the easiest way to address the issue with existing templates.

**Comment by ozzie-chung** [comment]
Ugh indeed. Thank you.

**Comment by trumanc** [comment]
This problem has now been fixed for the 3 values:

- Affordable housing supportive housing or recovery housing
- COVID-19 testing sites and laboratories and acquisition of related equipment
- Family or childcare

In all 3 cases now, even if the worksheet uploaded by the user contains an old/incorrect value for these dropdowns, the validations will recognize that value as correct, and the output csvs will include the corrected value.

We still don't know what the correct value is for a fourth option ("Mitigation measures in small businesses, nonprofits and impacted industries") and we've created a new issue to track that problem, since we need input from Treasury to resolve that. That issue is here: https://github.com/usdigitalresponse/arpa-reporter/issues/478
