### ISSUE TITLE
Update all field validation to match latest treasury requirements

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#460]
Reported mismatches from Ozzie on 2022-07-21

---

Project Upload Testing

18_229233

(Type_of_Capital_Expenditure__c) : Type of Capital Expenditure: bad value for restricted picklist field: &quot;Mitigation measures in small businesses, nonprofits and impacted industries&quot;
(Sub_Category__c) : bad value for restricted picklist field: 1.8-COVID-19 Assistance to Small Businesses
(Small_Businesses_Served__c) : Small Businesses Served is required for started projects with EC 1.8, 2.29-2.33
215218

(Type_of_Capital_Expenditure__c) : Type of Capital Expenditure: bad value for restricted picklist field: &quot;Affordable housing, supportive housing, or recovery housing&quot;
 

Subrecipient

(Unique_Entity_Identifier__c) : The UEI Number of VJH9NBK6Q2N3 is not a valid or unique UEI number.
 

Subaward

(Edited_Subaward_Amount_Explanation__c) : Award Amount has changed. Please provide an explanation.
(Place_of_Performance_Zip__c) : Zip code must be a 5 digit number
(Primary_Sector__c) : Primary Sector: bad value for restricted picklist field: Family or childcare
(Recipient_EIN__c) : [50354769](tel:50354769) Does not exist in the system. Please enter a valid EIN Number.
 

Expenditures > 50000

(Sub_Award_Lookup__c) : Subaward No is invalid
 

Expenditures < 50000

(Quarterly_Expenditure_Amt_Aggregates__c) : Total Period Expenditure Amount must be less than or equal to Cumulative Obligations

**Comment by ajhyndman** [comment]
OH also reports that no variation of "Mitigation measures in small businesses, nonprofits and impacted industries" seems to pass bulk upload validation in treasury.

**Comment by trumanc** [comment]
Here's a report on each of these issues and their cause/fix:

> (Type_of_Capital_Expenditure__c) : Type of Capital Expenditure: bad value for restricted picklist field: "Mitigation measures in small businesses, nonprofits and impacted industries"

We still don't know what the correct value is supposed to be here. We have a new ticket to track that issue, since it requires input from treasury. https://github.com/usdigitalresponse/arpa-reporter/issues/478

> (Sub_Category__c) : bad value for restricted picklist field: 1.8-COVID-19 Assistance to Small Businesses
(Small_Businesses_Served__c) : Small Businesses Served is required for started projects with EC 1.8, 2.29-2.33
215218

This was caused because the input cover sheet was set to EC 1.8, the project was added, then the user realized they were working on the wrong EC. They changed the EC and continued to add other projects. When the form was eventually uploaded, it included the (now hidden) 1.8 project incorrectly. That was fixed in https://github.com/usdigitalresponse/arpa-reporter/pull/466

> (Type_of_Capital_Expenditure__c) : Type of Capital Expenditure: bad value for restricted picklist field: "Affordable housing, supportive housing, or recovery housing"

This issue was tracked and fixed here: https://github.com/usdigitalresponse/arpa-reporter/issues/427

### Subrecipient

> (Unique_Entity_Identifier__c) : The UEI Number of VJH9NBK6Q2N3 is not a valid or unique UEI number.

This error occurs because the treasury won't allow you to edit existing subrecipients via bulk-upload. Admins will have to remove this from the export csv and manually update the recipient if there were changes.

### Subaward

> (Edited_Subaward_Amount_Explanation__c) : Award Amount has changed. Please provide an explanation.

This field isn't available in the bulk-upload files, so they have to be edited by admins in the Treasury portal input forms manually. We have an issue to track the feature request of allowing users to include this reason, so it can be shared with admins who have to make this update. That issue is here: https://github.com/usdigitalresponse/arpa-reporter/issues/445

> (Place_of_Performance_Zip__c) : Zip code must be a 5 digit number

Excel sometimes trims leading 0s from numeric values, which causes problems for RI zipcodes that start with a 0. This is related to another excel bug that we can't resolve until we get access to the Treasury portal again. That issue is being tracked here: https://github.com/usdigitalresponse/usdr-gost/issues/385

> (Primary_Sector__c) : Primary Sector: bad value for restricted picklist field: Family or childcare

This issue was tracked and fixed here: https://github.com/usdigitalresponse/arpa-reporter/issues/427

> (Recipient_EIN__c) : 50354769 Does not exist in the system. Please enter a valid EIN Number.

It looks like maybe a user typo'd a recipient id, since they are supposed to be 9 digit numbers?
We have an issue to track the request to add this validation to this tool: https://github.com/usdigitalresponse/usdr-gost/issues/382

### Expenditures > 50000

> (Sub_Award_Lookup__c) : Subaward No is invalid

This happens if a subrecipient was reported but they have no subawards yet. Admins should delete the subrecipient from the export.
We have an issue to track the request to add this validation to this tool: https://github.com/usdigitalresponse/usdr-gost/issues/382

### Expenditures < 50000

> (Quarterly_Expenditure_Amt_Aggregates__c) : Total Period Expenditure Amount must be less than or equal to Cumulative Obligations

This happened because of the accidental double-reporting of a project from an incorrect upload mentioned in the second issue above
